name: MincraMagics
version: 0.5.3
main: jp.mincra.mincramagics.MincraMagics
api-version: 1.20
authors: [Harineko]
depend: [NBTAPI, PlaceholderAPI]
softdepend:
  - Oraxen
  - CommandAPI
  - GSit
  - WorldGuard