name: MincraMagics
version: 0.7.2
main: jp.mincra.mincramagics.MincraMagics
api-version: 1.20
authors: [Harineko]
depend: [NBTAPI, PlaceholderAPI, CommandAPI, Oraxen, WorldGuard, LuckPerms]
softdepend:
  - GSit
  - Parties
  - DungeonMMO